(() => {
  const TC = () => window.TinkrCanvas;
  function buildToolbarHtml() {
    const groups = TC().TOOL_GROUPS, { move, region, shape, draw, text } = groups;
    const menu = (group, items) => items.map(v => `<button type="button" class="tinkr-tool-menu-item" data-tool-group="${group}" data-tool-variant="${v.id}"><span>${v.label}</span><kbd>${v.shortcut || ''}</kbd></button>`).join('');
    const tool = (group) => `<div class="tinkr-tool-group"><button type="button" class="tinkr-tool-btn ${group === 'move' ? 'active' : ''}" data-tool-trigger="${group}" aria-label="${groups[group].label} tools" title="${groups[group].label}">${groups[group].icon}</button><div class="tinkr-tool-menu tinkr-hide" data-menu="${group}">${menu(group, groups[group].variants)}</div></div>`;
    return `<div id="tinkr-toolbar" class="tinkr-toolbar" role="toolbar" aria-label="Tinkr canvas tools">${tool('move')}${tool('region')}${tool('shape')}${tool('draw')}${tool('text')}<button type="button" class="tinkr-tool-btn" data-tool-action="resources" aria-label="Resources" title="Resources">${TC().ICONS.resource}</button><span class="tinkr-tool-sep"></span><button type="button" class="tinkr-tool-btn" data-tool-action="hand" aria-label="Hand tool" title="Hand (H)">${TC().ICONS.hand}</button><button type="button" class="tinkr-tool-btn" data-tool-action="comment" aria-label="Add comment" title="Comment (C)">${TC().ICONS.comment}</button><span class="tinkr-tool-sep"></span><button type="button" class="tinkr-tool-btn" data-tool-action="present" aria-label="Present prototype" title="Present">${TC().ICONS.play}</button><button type="button" class="tinkr-tool-btn" data-tool-action="timeline" aria-label="Motion timeline" title="Motion">${TC().ICONS.motion}</button><button type="button" class="tinkr-tool-btn tinkr-dev-toggle" data-tool-action="devmode" title="Dev Mode">&lt;/&gt;</button></div><div id="tinkr-timeline" class="tinkr-timeline tinkr-hide"><div class="tinkr-timeline-bar"><button type="button" data-timeline="play">${TC().ICONS.play}</button><button type="button" data-timeline="keyframe">◆</button><span class="tinkr-timeline-time">0 ms</span><div class="tinkr-timeline-ruler"></div></div><div id="tinkr-timeline-tracks" class="tinkr-timeline-tracks"></div></div><svg id="tinkr-vector-layer" class="tinkr-vector-layer"></svg><div id="tinkr-dev-overlay" class="tinkr-dev-overlay tinkr-hide"></div><div id="tinkr-scale-handles" class="tinkr-scale-handles tinkr-hide"></div>`;
  }
  function mountToolbar(root, handlers) { root.insertAdjacentHTML('beforeend', buildToolbarHtml()); const toolbar = root.querySelector('#tinkr-toolbar'); const closeMenus = () => toolbar.querySelectorAll('.tinkr-tool-menu').forEach(m => m.classList.add('tinkr-hide')); toolbar.querySelectorAll('[data-tool-trigger]').forEach(btn => btn.addEventListener('click', e => { e.stopPropagation(); const menu = toolbar.querySelector(`[data-menu="${btn.dataset.toolTrigger}"]`); const open = menu.classList.contains('tinkr-hide'); closeMenus(); if (open) menu.classList.remove('tinkr-hide'); })); toolbar.querySelectorAll('[data-tool-group]').forEach(btn => btn.addEventListener('click', e => { e.stopPropagation(); handlers.setTool(btn.dataset.toolGroup, btn.dataset.toolVariant); closeMenus(); })); toolbar.querySelector("[data-tool-action='hand']")?.addEventListener('click', () => handlers.setTool('move', 'hand')); toolbar.querySelector("[data-tool-action='comment']")?.addEventListener('click', () => handlers.setTool('comment', 'pin')); toolbar.querySelector("[data-tool-action='devmode']")?.addEventListener('click', () => handlers.toggleDevMode()); toolbar.querySelector("[data-tool-action='timeline']")?.addEventListener('click', () => handlers.toggleTimeline()); toolbar.querySelector("[data-tool-action='present']")?.addEventListener('click', () => handlers.enterPresent()); toolbar.querySelector("[data-tool-action='resources']")?.addEventListener('click', () => handlers.openResources()); document.addEventListener('click', closeMenus); return toolbar; }
  function syncToolbar(root, tool) { const toolbar = root?.querySelector('#tinkr-toolbar'); if (!toolbar) return; toolbar.querySelectorAll('[data-tool-trigger]').forEach(btn => btn.classList.toggle('active', btn.dataset.toolTrigger === tool.group && !tool.devMode)); toolbar.querySelector('.tinkr-dev-toggle')?.classList.toggle('active', tool.devMode); toolbar.querySelector("[data-tool-action='hand']")?.classList.toggle('active', tool.group === 'move' && tool.variant === 'hand'); toolbar.querySelector("[data-tool-action='comment']")?.classList.toggle('active', tool.group === 'comment'); }
  window.TinkrToolbar = { mountToolbar, syncToolbar, buildToolbarHtml };
})();
